CREATE TABLE stores_data (
    id SERIAL PRIMARY KEY,
    site_id VARCHAR(50),
    router VARCHAR(50),
    date_timestamp VARCHAR(50),
    mac_primary VARCHAR(50),
    mac_backup VARCHAR(50),
    mac_third VARCHAR(50),
    gtw_primary VARCHAR(50),
    gtw_backup VARCHAR(50),
    gtw_third VARCHAR(50),
    public_ip_primary VARCHAR(50),
    public_ip_backup VARCHAR(50),
    public_ip_third VARCHAR(50),
    provider_primary VARCHAR(50),
    provider_backup VARCHAR(50),	
    provider_third VARCHAR(50),
    status_primary VARCHAR(50),
    status_backup VARCHAR(50),
    status_third VARCHAR(50),
    loopback_0 VARCHAR(50),
    loopback_1 VARCHAR(50),
    loopback_2 VARCHAR(50),
    loopback_3 VARCHAR(50),
    loopback_0_24h VARCHAR(50),
    loopback_1_24h VARCHAR(50),
    loopback_2_24h VARCHAR(50),
    loppback_3_24h VARCHAR(50),
    imsi VARCHAR(50),
    region VARCHAR(50),
    longitude VARCHAR(50),
    latitude VARCHAR(50),
    city VARCHAR(50),
    province VARCHAR(50),
    primary_mac_model VARCHAR(50),
    backup_mac_model VARCHAR(50),
    serial_number VARCHAR(50)
)
